#include "stdafx.h"

#include "CheckingBasics.h"

TYPE_MIRROR enum SystemEvent
{
	ESYSTEM_EVENT_RANDOM_SEED_check = 1,
	ESYSTEM_EVENT_RANDOM_ENABLE_check,
	ESYSTEM_EVENT_RANDOM_DISABLE_check,
	ESYSTEM_EVENT_CHANGE_FOCUS_check = 10,
	ESYSTEM_EVENT_MOVE_check = 11,
	ESYSTEM_EVENT_RESIZE_check = 12,
	ESYSTEM_EVENT_ACTIVATE_check = 13,
	ESYSTEM_EVENT_POS_CHANGED_check = 14,
	ESYSTEM_EVENT_STYLE_CHANGED_check = 15,
	ESYSTEM_EVENT_LEVEL_LOAD_START_PRELOADINGSCREEN_check,
	ESYSTEM_EVENT_LEVEL_LOAD_RESUME_GAME_check,
	ESYSTEM_EVENT_LEVEL_LOAD_PREPARE_check,
	ESYSTEM_EVENT_LEVEL_LOAD_START_LOADINGSCREEN_check,
	ESYSTEM_EVENT_LEVEL_LOAD_LOADINGSCREEN_ACTIVE_check,
	ESYSTEM_EVENT_LEVEL_LOAD_START_check,
	ESYSTEM_EVENT_LEVEL_LOAD_END_check,
	ESYSTEM_EVENT_LEVEL_LOAD_ERROR_check,
	ESYSTEM_EVENT_LEVEL_NOT_READY_check,
	ESYSTEM_EVENT_LEVEL_PRECACHE_START_check,
	ESYSTEM_EVENT_LEVEL_PRECACHE_FIRST_FRAME_check,
	ESYSTEM_EVENT_LEVEL_GAMEPLAY_START_check,
	ESYSTEM_EVENT_LEVEL_UNLOAD_check,
	ESYSTEM_EVENT_LEVEL_POST_UNLOAD_check,
	ESYSTEM_EVENT_GAME_POST_INIT_check,
	ESYSTEM_EVENT_GAME_POST_INIT_DONE_check,
	ESYSTEM_EVENT_FULL_SHUTDOWN_check,
	ESYSTEM_EVENT_FAST_SHUTDOWN_check,
	ESYSTEM_EVENT_LANGUAGE_CHANGE_check,
	ESYSTEM_EVENT_TOGGLE_FULLSCREEN_check,
	ESYSTEM_EVENT_SHARE_SHADER_COMBINATIONS_check,
	ESYSTEM_EVENT_3D_POST_RENDERING_START_check,
	ESYSTEM_EVENT_3D_POST_RENDERING_END_check,
	ESYSTEM_EVENT_SWITCHING_TO_LEVEL_HEAP_check,
	ESYSTEM_EVENT_SWITCHED_TO_LEVEL_HEAP_check,
	ESYSTEM_EVENT_SWITCHING_TO_GLOBAL_HEAP_check,
	ESYSTEM_EVENT_SWITCHED_TO_GLOBAL_HEAP_check,
	ESYSTEM_EVENT_LEVEL_PRECACHE_END_check,
	ESYSTEM_EVENT_GAME_MODE_SWITCH_START_check,
	ESYSTEM_EVENT_GAME_MODE_SWITCH_END_check,
	ESYSTEM_EVENT_VIDEO_check,
	ESYSTEM_EVENT_GAME_PAUSED_check,
	ESYSTEM_EVENT_GAME_RESUMED_check,
	ESYSTEM_EVENT_TIME_OF_DAY_SET_check,
	ESYSTEM_EVENT_EDITOR_ON_INIT_check,
	ESYSTEM_EVENT_FRONTEND_INITIALISED_check,
	ESYSTEM_EVENT_EDITOR_GAME_MODE_CHANGED_check,
	ESYSTEM_EVENT_EDITOR_SIMULATION_MODE_CHANGED_check,
	ESYSTEM_EVENT_FRONTEND_RELOADED_check,
	ESYSTEM_EVENT_SW_FORCE_LOAD_START_check,
	ESYSTEM_EVENT_SW_FORCE_LOAD_END_check,
	ESYSTEM_EVENT_SW_SHIFT_WORLD_check,
	ESYSTEM_EVENT_STREAMING_INSTALL_ERROR_check,
	ESYSTEM_EVENT_ONLINE_SERVICES_INITIALISED_check,
	ESYSTEM_EVENT_AUDIO_IMPLEMENTATION_LOADED_check,
	ESYSTEM_EVENT_USER_check = 0x1000,
	ESYSTEM_BEAM_PLAYER_TO_CAMERA_POS_check
};

#define CHECK_ENUM(x) static_assert (SystemEvent::x ## _check == ESystemEvent::x, "ESystemEvent enumeration has been changed.")

inline void Check()
{
	CHECK_ENUM(ESYSTEM_EVENT_RANDOM_SEED);
	CHECK_ENUM(ESYSTEM_EVENT_RANDOM_ENABLE);
	CHECK_ENUM(ESYSTEM_EVENT_RANDOM_DISABLE);
	CHECK_ENUM(ESYSTEM_EVENT_CHANGE_FOCUS);
	CHECK_ENUM(ESYSTEM_EVENT_MOVE);
	CHECK_ENUM(ESYSTEM_EVENT_RESIZE);
	CHECK_ENUM(ESYSTEM_EVENT_ACTIVATE);
	CHECK_ENUM(ESYSTEM_EVENT_POS_CHANGED);
	CHECK_ENUM(ESYSTEM_EVENT_STYLE_CHANGED);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_LOAD_START_PRELOADINGSCREEN);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_LOAD_RESUME_GAME);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_LOAD_PREPARE);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_LOAD_START_LOADINGSCREEN);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_LOAD_LOADINGSCREEN_ACTIVE);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_LOAD_START);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_LOAD_END);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_LOAD_ERROR);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_NOT_READY);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_PRECACHE_START);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_PRECACHE_FIRST_FRAME);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_GAMEPLAY_START);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_UNLOAD);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_POST_UNLOAD);
	CHECK_ENUM(ESYSTEM_EVENT_GAME_POST_INIT);
	CHECK_ENUM(ESYSTEM_EVENT_GAME_POST_INIT_DONE);
	CHECK_ENUM(ESYSTEM_EVENT_FULL_SHUTDOWN);
	CHECK_ENUM(ESYSTEM_EVENT_FAST_SHUTDOWN);
	CHECK_ENUM(ESYSTEM_EVENT_LANGUAGE_CHANGE);
	CHECK_ENUM(ESYSTEM_EVENT_TOGGLE_FULLSCREEN);
	CHECK_ENUM(ESYSTEM_EVENT_SHARE_SHADER_COMBINATIONS);
	CHECK_ENUM(ESYSTEM_EVENT_3D_POST_RENDERING_START);
	CHECK_ENUM(ESYSTEM_EVENT_3D_POST_RENDERING_END);
	CHECK_ENUM(ESYSTEM_EVENT_SWITCHING_TO_LEVEL_HEAP);
	CHECK_ENUM(ESYSTEM_EVENT_SWITCHED_TO_LEVEL_HEAP);
	CHECK_ENUM(ESYSTEM_EVENT_SWITCHING_TO_GLOBAL_HEAP);
	CHECK_ENUM(ESYSTEM_EVENT_SWITCHED_TO_GLOBAL_HEAP);
	CHECK_ENUM(ESYSTEM_EVENT_LEVEL_PRECACHE_END);
	CHECK_ENUM(ESYSTEM_EVENT_GAME_MODE_SWITCH_START);
	CHECK_ENUM(ESYSTEM_EVENT_GAME_MODE_SWITCH_END);
	CHECK_ENUM(ESYSTEM_EVENT_VIDEO);
	CHECK_ENUM(ESYSTEM_EVENT_GAME_PAUSED);
	CHECK_ENUM(ESYSTEM_EVENT_GAME_RESUMED);
	CHECK_ENUM(ESYSTEM_EVENT_TIME_OF_DAY_SET);
	CHECK_ENUM(ESYSTEM_EVENT_EDITOR_ON_INIT);
	CHECK_ENUM(ESYSTEM_EVENT_FRONTEND_INITIALISED);
	CHECK_ENUM(ESYSTEM_EVENT_EDITOR_GAME_MODE_CHANGED);
	CHECK_ENUM(ESYSTEM_EVENT_EDITOR_SIMULATION_MODE_CHANGED);
	CHECK_ENUM(ESYSTEM_EVENT_FRONTEND_RELOADED);
	CHECK_ENUM(ESYSTEM_EVENT_SW_FORCE_LOAD_START);
	CHECK_ENUM(ESYSTEM_EVENT_SW_FORCE_LOAD_END);
	CHECK_ENUM(ESYSTEM_EVENT_SW_SHIFT_WORLD);
	CHECK_ENUM(ESYSTEM_EVENT_STREAMING_INSTALL_ERROR);
	CHECK_ENUM(ESYSTEM_EVENT_ONLINE_SERVICES_INITIALISED);
	CHECK_ENUM(ESYSTEM_EVENT_AUDIO_IMPLEMENTATION_LOADED);
	CHECK_ENUM(ESYSTEM_EVENT_USER);
	CHECK_ENUM(ESYSTEM_BEAM_PLAYER_TO_CAMERA_POS);
}